name: v0-build
services: 
  db: 
    image: postgres:latest
    environment: 
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=postgres
    ports: 
      - 5431:5432
      